server:
  port: 9090

spring:
  profiles:
    active: dev
  datasource:
        name: spiketest
        url: jdbc:mysql://localhost:3306/spike_system
        username: root
        password: 
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/wpp/spike/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wpp.spike.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql